arb-dir: lib/l10n
template-arb-file: es.arb
output-localization-file: app_localizations.dart
output-class: AppLocalizations
synthetic-package: false
nullable-getter: false
untranslated-messages-file: missing_translations.txt
